# Generated by Django 4.0.1 on 2022-01-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Город'),
        ),
    ]
